### ISSUE TITLE
Missouri and Indiana datasets are swapped

### ISSUE THREAD

**Issue by Hain0** [CAVaccineInventory/vaccine-feed-ingest#109]
Hello,

The fetched / parsed data for Missouri (https://raw.githubusercontent.com/CAVaccineInventory/vaccine-feed-ingest-results/main/mo/arcgis/parsed/46630b2520ce44a68a9f42f8343d3518_0.parsed.ndjson) contains Indiana addresses, and vice versa.

**Comment by eliblock** [comment]
Thank you for noticing this @Hain0 - it should now be fixed!

Be sure to rebase your PR (#111) on top of the new main branch and put your normalizer in the correct place (it seems like you are writing `in/arcgis`).
