### ISSUE TITLE
normalize arcgis from Tennessee

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#116]
[![learn our pipeline: normalize](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=normalize&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Blocked on #115 

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/schema/schema.py).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch tn/arcgis
    poetry run vaccine-feed-ingest parse tn/arcgis
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize tn/arcgis
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/normalized)

**Comment by LeeMallabone** [comment]
I can take a pass at this.

**Comment by LeeMallabone** [comment]
Looking more closely at the fetched data from #114, I think it's only testing sites and it's hard to tell if any are distributing vaccines. @eliblock is still still useful to create a normalizer for it?
For example:
```            
"attributes": {
    "AccessType": "Drive-thru",
    "Address": "5001 Gallatin Pike Suite 1",
    "Availability": "Public",
    "City": "Nashville",
    "County": "Davidson",
    "FID": 506,
    "Hours": "M-F 7a-3p, Sat 9a-1p",
    "Id": null,
    "Name": "Crescent Community Health Services",
    "Notes": "Rapid Tests are $125 per test. Not accepting insurance at this time. Please call 615-902-5259 for appointment",
    "Notes_ES": null,
    "Phone": "(615) 902-5259",
    "Spanish": null,
    "State": "TN",
    "WkEndHrs": null,
    "ZIP": 37216
},
"geometry": {
    "spatialReference": {
        "latestWkid": 4326,
        "wkid": 4326
    },
    "x": -86.72526944925042,
    "y": 36.23304480683498
}
```

**Comment by eliblock** [comment]
Hi @LeeMallabone - thank you for taking a close look at the data!

I went back to the [original source link](https://experience.arcgis.com/experience/885e479b688b4750837ba1d291b85aed), and it looks like it is indeed _testing_ data not _vaccination location_ data.

Based on that we should _not_ write the normalizer here. Thank you for helping prevent improper data from making its way through the pipeline!

**Comment by MoralCode** [comment]
it appears to me that there are no vaccine-related layers (from their services page https://services1.arcgis.com/YuVBSS7Y1of2Qud1/ArcGIS/rest/services) that are for vaccination locations. seems to be only testing locations or county-wide info like what phase they are in.

**Comment by MoralCode** [comment]
The state seems to not provide vaccination site locations, but these states may be covered by existing national datasets (mainly the one from GISCorps) that's based on crowdsourced locations. My recommendation would be to either encourage the state to make this data available or contribute info on sites in TN to the GISCorps dataset (link: https://covid-19-giscorps.hub.arcgis.com/). They have forms for single-entry and a spreadsheet template for bulk entry and their volunteers validate it. Once the data is in the GIScorps system it will get pulled in by this repo
