### ISSUE TITLE
normalize GisCorps national data

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#121]
[![learn our pipeline: normalize](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=normalize&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/schema/schema.py).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch us/giscorps_vaccine_providers
    poetry run vaccine-feed-ingest parse us/giscorps_vaccine_providers
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize us/giscorps_vaccine_providers
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/normalized)

**Comment by eliblock** [comment]
@MoralCode - are you interested in taking this one on?

**Comment by MoralCode** [comment]
yep! i'll take a shot at this

**Comment by MoralCode** [comment]
I think Ive got a decent WIP going on this but there's some weird edge cases  (like `"Wheelchair_Accessible": "Unknown",`) that may need to be resolved by someone more familiar with the normalized schema as this may warrant a change in schema (possibly).

In #119 I linked some docs that link to the schema definitions for the GIScorps data that may be helpful here. here's the links to that schema more directly:
- https://docs.google.com/document/d/1z8wCoA91asxuvNmZ4Nsb-4IF8jKyZeUKVyRpUr4Xef8/edit
- https://docs.google.com/document/d/1xqZDHtkNHfelez2Rm3mLAKTwz7gjCAMJaMKK_RxK8F8/edit#heading=h.1vlfv6pko85z

I'll make a draft PR with my WIP changes so far so someone can pick this up where I left off

**Comment by MoralCode** [comment]
weather update: got kinda distracted. now working on a [python library](https://github.com/MoralCode/jsonify-opening-hours) to parse the operating hours from the seemingly arbitrary string as present in the `operhours` field

**Comment by MoralCode** [comment]
once/if #267 is merged this should be ready to go apart from the operating hours field which still isn't done. is this important enough/necessary to have before merging?
