### ISSUE TITLE
fetch prepmod from WA

### ISSUE THREAD

**Issue by jakepusateri** [CAVaccineInventory/vaccine-feed-ingest#122]
[![learn our pipeline: fetch](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=fetch&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://prepmod.doh.wa.gov/clinic/search

Put your script in a file named:  `wa/prepmod/fetch.py`

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch wa/prepmod
    ```

**Comment by jakepusateri** [comment]
In WA, many of the mass vaccination sites use prepmod for availability and scheduling. I have a script that's alerting a discord with new results here that I can adapt if this data would be useful.

**Comment by eliblock** [comment]
Hi @jakepusateri - that certainly sounds useful, and we welcome the contribution! I'm going to open additional issues to _parse_ and then _normalize_ the data from prepmod as well (check the wiki for the meaning of the three phases).

One thing to keep in mind - some other states use prepmod as well (for example, [RI](https://www.vaccinateri.org/clinic/search)). It would be exciting if we could use your to-be-adapted script to fetch data in these other states as well (you don't _have_ to do this, but it would be cool!).
