### ISSUE TITLE
parse prepmod from WA 

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#123]
[![learn our pipeline: parse](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=parse&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#parse)

Blocked on #122 

Parse existing data into [`.ndjson`](http://ndjson.org/).

Read all files in the directory passed as the second argument (`sys.argv[2]`), convert them to `.ndjson`, and then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the parse stage and how to get set up for development!

### Tips

1. Fetch data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch wa/prepmod
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest parse wa/prepmod
    ```

### Example
[Fetched files for `md/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/raw) are converted to [parsed files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/md/arcgis/parsed)

**Comment by matthewg** [comment]
Taking a look: https://github.com/CAVaccineInventory/vaccine-feed-ingest/compare/main...matthewg:wa_parse

**Comment by eliblock** [comment]
Hi @matthewg & @jakepusateri - it looks like you both did some good work to set up a parser for `wa/prepmod`?

Would it be possible for you two to collaborate - perhaps through a quick discussion in the comments here - to combine your approaches as needed? Since you've both spent some time looking at this data, I want to make sure the parser that ends up getting merged includes both of your expertise!

**Comment by matthewg** [comment]
I like @jakepusateri 's better, I think it will get a pure superset of the data from mine, and the code is cleaner. Why don't we just go with that one.
