### ISSUE TITLE
fetch Florida, Georgia, and Colorado sites from FindYourVaccine.org

### ISSUE THREAD

**Issue by MoralCode** [CAVaccineInventory/vaccine-feed-ingest#161]
[![learn our pipeline: fetch](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=fetch&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://docs.google.com/spreadsheets/d/1124pvazfFxhHkfFldcdrhSoh8DlpPwu0QvUskupEiG0 (Both FL and CO sheets)

Put your script in files named: `fl/findyourvaccine_locations`, `ga/findyourvaccine_locations` and `co/findyourvaccine_locations`

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch fl/findyourvaccine_locations
   poetry run vaccine-feed-ingest fetch co/findyourvaccine_locations
   poetry run vaccine-feed-ingest fetch ga/findyourvaccine_locations
    ```

**Comment by MoralCode** [comment]
I'll work on this. seems like it might be useful to make this a generic google drive fetcher (are there other data sources that are in google drive or that are CSV?

**Comment by obra** [comment]
almost certainly. but it’s worth asking fyv if they have an api

**Comment by MoralCode** [comment]
i believe that the google drive is acting as their cache for (I think) airtable and is what is serving the live data. i have asked in their discord though to see if that is still the canonical source for accessing their vaccination site location data

**Comment by MoralCode** [comment]
here is some [code](https://github.com/VacFind/GeoCompare/blob/main/fetchers/googledrive.py) i already wrote to grab CSV data from google sheets. if FYV doesn't have an API. I'll likely reuse this and turn it into a fetcher

**Comment by edcous** [comment]
Looking through the last contacted timestamp it appears none of them have been updated in the past month, so it may be worth double checking that all the sites are still offering vaccines (assuming they aren't all just pharmacies).

**Comment by MoralCode** [comment]
@edcous yeah from my asking on discord i suspect this sheet isn't being actively updated anymore. have asked whether it could still be useful for the locations or if its not worth adding it
