### ISSUE TITLE
Strip leading zeros from Walgreens store IDs

### ISSUE THREAD

**Issue by nschiefer** [CAVaccineInventory/vaccine-feed-ingest#165]
We currently fail to match many Walgreens locations because the store IDs are padded with leading zeros (and the existing concordances don't have this).

This requires modifying the regex in `provider_id_from_location_name()`.

**Comment by cdjj** [comment]
Would it make sense to do this more broadly?  This is the case for CVS (https://github.com/CAVaccineInventory/vaccine-feed-ingest/pull/135/files#) in `provider_id_from_name`....

**Comment by nschiefer** [comment]
Yes, I don't currently know of a pharmacy numbering scheme where leading zeros are significant!

Thanks so much for doing CVS @cdjj! If you're interested, we will probably want... a lot more of these, since retail pharmacies tend to vary by region.

I can get you a list of examples sometime tomorrow. If you're interested in the meantime, you should be able to run the fetch stage of the ingest pipeline locally (instructions are on the wiki) and take a look at what kinds of formats we see!

**Comment by cdjj** [comment]
Sure, I can poke at this in a couple hours; feel free to assign it to me.
