### ISSUE TITLE
Generic static-content fetcher

### ISSUE THREAD

**Issue by cdjj** [CAVaccineInventory/vaccine-feed-ingest#190]
Rather than rewriting variations on simple hit-URL-and-save-it fetchers (e.g. [ca/sf_gov/fetch.sh](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/runners/ca/sf_gov/fetch.sh) , [me/maine_gov/fetch.py](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/runners/me/maine_gov/fetch.py)), maybe it makes sense to write a generic one and have config data in the runners directory, much like for arcgis.  Thoughts?

**Comment by eliblock** [comment]
Great idea! `vaccine_feed_ingest/runners/_shared/fetch.py` should be easy to refactor to support multiple configurations (`vaccine_feed_ingest/runners/_shared/parse.py` is an example), and this setup should save time for the "simple" fetches!

**Comment by shashank025** [comment]
I'll take this one.

**Comment by shashank025** [comment]
Sorry, but this seems like a lot of work for a minor gain. I'll try and contribute elsewhere for now, so I'll give this up.
