### ISSUE TITLE
normalize sfsites from il

### ISSUE THREAD

**Issue by rossry** [CAVaccineInventory/vaccine-feed-ingest#215]
[![learn our pipeline: normalize](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=normalize&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/schema/schema.py).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch il/sfsites
    poetry run vaccine-feed-ingest parse il/sfsites
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize il/sfsites
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/normalized)

**Comment by shaqq** [comment]
Hi @rossry - I'm new to this project, but I had a quick question - do we need a parser for il/sfsites before we do this? If so, I'm happy to tackle that.

**Comment by shaqq** [comment]
@rossry did you want to tackle this one? i can take it on if not

**Comment by rossry** [comment]
@shaqq you can take it! It requires #213 for `parse il/sfsites` to work, but that's been accepted, so you've got a green light.

**Comment by eliblock** [comment]
FYI @shaqq - with #213 merged, I think we're ready to normalize this! Based on your earlier comment I assigned the issue to you.
