### ISSUE TITLE
Fix normalized records for vaxfinder

### ISSUE THREAD

**Issue by bryanculbertson** [CAVaccineInventory/vaccine-feed-ingest#223]
1. Record needs an "id" field
2. "source" needs an "id" field

Bad Record Log:
```
04/26/2021 22:29:07 WARNING:load:Skipping source location because it is invalid: ***"name": "CVS (Centre Ave.)", "385 Centre Ave, Abington, MA 02351": ***"street1": "385 Centre Ave", "street2": null, "city": "Abington", "state": "MA", "zip": "02351"***, "contact": [***"contact_type": "booking", "website": "https://vaxfinder.mass.gov"***], "fetched_at": "2021-04-25T12:10:31.844763", "source": ***"source": "vaxfinder", "fetched_from_uri": "https://www.mass.gov/doc/covid-19-vaccine-locations-for-currently-eligible-recipients-csv/download", "fetched_at": "2021-04-25T12:10:31.844763", "data": ***"name": "Abington: CVS (Centre Ave.)", "address": "385 Centre Ave, Abington, MA 02351"***
```

Validation Failure:
```
2 validation errors for NormalizedLocation
id
  field required (type=value_error.missing)
source -> id
  field required (type=value_error.missing)
```

**Comment by shaqq** [comment]
hm there's no id-like field in the raw excel sheet. here's an example row:

(sorry if this looks weird, it's copy/paste from excel)

```

Location Name | Serves | Full Address | Site Type | Find an appointment | Phone | E-mail | Appointment info | Instructions at site | Accessibility | Days of the week open | Website
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Abington: CVS (Centre Ave.) | All eligible people statewide | 385 Centre Ave, Abington, MA 02351 | Indoor | https://vaxfinder.mass.gov | 800-SHOP-CVS (1-800-746-7287) |   |   | Check-in 15min prior |   | Daily | https://vaxfinder.mass.gov
```

we could take the hashcode of the address perhaps to get a unique id, possibly? is there a "default" id to use if there is none?

**Comment by bryanculbertson** [comment]
@shaqq For this feed the best option does look like a hash of address. It isn't ideal of course, but I can't think of anything better.

**Comment by MoralCode** [comment]
I was literally about to comment the same thing: hash or generate a UUID deterministically (is this a thing?) based some unique aspect of the record like the coordinates or the address. Would it help if I created some reusable code to do this so it could be used as a default ID generation method?

**Comment by shaqq** [comment]
i'll get a PR out for this soon

@MoralCode Maybe we can open a new GH issue to create a consistent default? We can even hash the entire JSON, as a checksum of sorts.

**Comment by rossry** [comment]
@shaqq I don't think we even need a hash here -- using the string f"{location_name}:{full_address}" is basically what @tmb and I decided to do in #220.

**Comment by shaqq** [comment]
@rossry Yeah, in my PR (#239) I do exactly that, but for a more generic solution that'd automagically default a unique id, it's probably safe to do the whole hash.

Maybe there's corner cases around two pharmacies sharing the same address and name if we parse it wrong? 

Either way, it wouldn't hurt too much, but we can prob discuss further in a separate GH issue if we decide to go down this path of a generic default id.
