### ISSUE TITLE
convert outstanding existing normalize stages to use typed helpers

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#233]
[![learn our pipeline: normalize](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=normalize&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Some of the earliest-created normalizers construct the output `.ndjson` directly (rather than using the [packaged schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema)). This means that they do not benefit from type-checking, will not benefit from improvements we plan to make to the package (e.g., auto-`.strip()`-ing strings), and generally make the pipeline more fragile as we iterate on shared components.

Update the following normalizers to use the [published/packaged schema helpers](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema):
- [x] `ca/sf_gov`
- [x] `ct/covidvaccinefinder_gov`
- [x] `ma/vaxfinder_gov` (note: this site will also be updated in #223)
- [x] `ny/am_i_eligible_covid19vaccine_gov` (note: mostly uses the schema helpers, but appends partial addresses directly)
- [x] `us/vaccinespotter_org`

<hr />

To import the schema helpers:

```python
from vaccine_feed_ingest_schema import schema
```

<hr />

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch <state>/<site>
    poetry run vaccine-feed-ingest parse <state>/<site>
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize <state>/<site>
    ```

**Comment by shaqq** [comment]
currently tackling ca/sf_gov right now

**Comment by shaqq** [comment]
PR out!

**Comment by eliblock** [comment]
Thank you!

FYI, we updated the schema for address earlier today to make all fields optional. If you re-install the poetry dependencies, you should pick that up! I'll update the wiki now.

**Comment by shaqq** [comment]
👍 just updated my PR

#276 _should_ cover the rest of this then, but would be good to have someone double-check

**Comment by eliblock** [comment]
It looks to me like they have all been converted!

As I mentioned in my review of #276, it looks like there are a few places we will need to continue tweaking to fully take advantage of the schema, but per #278 it seems like it makes sense to wait for the validations to be in place before taking another look.

**Comment by shaqq** [comment]
@eliblock Gotcha - maybe it'd be easier to close this issue out, since we covered a lot of the work, and then when the new validators come into play we'll create new issues where we see validation errors.

Btw I just opened #288 to fix one line that I missed
