### ISSUE TITLE
Put phone numbers w/o area codes into the notes section in me/maine_gov normalizer

### ISSUE THREAD

**Issue by tmb** [CAVaccineInventory/vaccine-feed-ingest#236]
Some phone numbers from the `me/maine_gov` don't have area codes. Right now, if this happens, the phone number just isn't included. 

It'd be great if, instead of being removed, phone numbers without area codes were included in the notes.

**Comment by cdjj** [comment]
Maine only has one area code; why  not just fill it in?

**Comment by eliblock** [comment]
That works! We weren't sure if `207` encompassed all of Maine or not.

**Comment by rossry** [comment]
Is that true? Some entries in the parsed file have 207, others 866, and others 877.

**Comment by rossry** [comment]
Oh, answered my own question with a little Google -- 866 and 877 are toll-free national codes, like 800 or 888.

Can't get the auto-207 now, maybe after work in ~~9 hours.
