### ISSUE TITLE
Expand `provider_id_name()` to cover more chains

### ISSUE THREAD

**Issue by nschiefer** [CAVaccineInventory/vaccine-feed-ingest#254]
We have a function (`provider_id_from_name()`) that tries to parse retail pharmacy store numbers from a string with the location's name (e.g., "Walgreens #7150 -> 7150).

We want to support this on every chain of retail pharmacies that we know about.

**Comment by tiffting** [comment]
Who all is missing from [`provider_id_from_name()`](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/e72eb49e21bac6da07effc0abdad1af0df19e109/vaccine_feed_ingest/utils/normalize.py#L8)? Is there an [authoritative list](https://en.wikipedia.org/wiki/List_of_pharmacies#United_States) of retail pharmacy chains we're looking to support?

**Comment by tiffting** [comment]
Here's the [CDC's list](https://www.cdc.gov/vaccines/covid-19/retail-pharmacy-program/participating-pharmacies.html) of participating pharmacies.

**Comment by nschiefer** [comment]
The target is to understand as many of the formats that we already have. There are a few ways that we could get this. The easiest _might_ be to the run the fetcher/parser/normalizer phases locally (using the instructions on this repo's wiki) and look for patterns. Alternatively, I could dump the list of places that we've found so far from our database.

**Comment by nschiefer** [comment]
Here is a random sample of 10k location names, which should be pretty representative of what we're hoping to parse. [select-name-from-location-orded0ba3a.csv](https://github.com/CAVaccineInventory/vaccine-feed-ingest/files/6388621/select-name-from-location-orded0ba3a.csv)

**Comment by shashank025** [comment]
I can take this one.

**Comment by shashank025** [comment]
@nschiefer thanks so much for that csv file. I examined it a bit, via:

```
$ sort select-name-from-location-orded0ba3a.csv | uniq | less
```

and I see a bunch of patterns, including some that are _not_ currently handled:

```
CVS Pharmacy, Inc. #00052
CVS Pharmacy, Inc. #00076
...
Community, A Walgreens Pharmacy #13434
Community, A Walgreens Pharmacy #13435
...
Walmart Inc, #1828
Walmart Inc, #2271
Walmart Inc, #2509
...
Acme Pharmacy #1058
Acme Pharmacy #1077
Acme Pharmacy #1092
...
Albertsons Companies Inc. #3311
Albertsons Market Pharmacy #1915
Albertsons Market Pharmacy #3917
Albertsons Market Pharmacy #665
Albertsons Market Pharmacy #905
Albertsons Pharmacy #232
Albertsons Pharmacy #4267
Albertsons Pharmacy 0226
...
Baker's Pharmacy #61500300
Baker's Pharmacy #61500316
Baker's Pharmacy #61500318
...
COSTCO PHARMACY #133
COSTCO PHARMACY #144
COSTCO PHARMACY #401
...
...
```

It seems like I can add regexes to extract the ids without too much effort. 

**Question:**

As for extracting a **provider_name**, unless its one of the [supported VaccineProviders](https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema/blob/d1bd7cf8706a5f7f8b9811dadb3d7c8afb026bcb/vaccine_feed_ingest_schema/location.py#L182), it looks like I should just come up with a reasonable scheme.

So, for example, I expect to produce:

```
>>> provider_id_from_name("COSTCO PHARMACY #133")
("costco", "133")
>>> provider_id_from_name("Baker's Pharmacy #61500300")
("bakers_pharmacy", "61500300")
```

Does that seem reasonable?

**Comment by nschiefer** [comment]
@shashank025 Glad that the CSV was useful! I'm not surprised that there are a bunch that we haven't handled yet; our code was mostly developed to handle California, and pharmacy chains are often regional.

For `provider_name`, definitely use a `VaccineProvider` if we have one, and pick a reasonable normalization otherwise. If you can, it would be great to open a PR on the https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema repository to add the new providers!

**Comment by shashank025** [comment]
> @shashank025 Glad that the CSV was useful! I'm not surprised that there are a bunch that we haven't handled yet; our code was mostly developed to handle California, and pharmacy chains are often regional.

Makes sense.

> For `provider_name`, definitely use a `VaccineProvider` if we have one, and pick a reasonable normalization otherwise. If you can, it would be great to open a PR on the https://github.com/CAVaccineInventory/vaccine-feed-ingest-schema repository to add the new providers!

Will do.
