### ISSUE TITLE
[refactoring] Reuse the logic for determining the scraper executable and yml files across cli.py and site.py

### ISSUE THREAD

**Issue by shashank025** [CAVaccineInventory/vaccine-feed-ingest#255]
There are currently two code locations which do pretty much the same things:

* Location 1: [cli.py#_compute_has_fetch()](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/4458287104d03b71cc06dd375fe2b07b3d922f3c/vaccine_feed_ingest/cli.py#L99)
* Location 2: [ingest.py#run_fetch()](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/4458287104d03b71cc06dd375fe2b07b3d922f3c/vaccine_feed_ingest/stages/ingest.py#L19)

In both locations, the _things_ being done are the following:
* determine the executable (if there is one)
* determine the yml resource file to supply to the executable

**Proposal:**

Unify the associated logic so it can be reused across these two modules.

**Why?**

- DRY will prevent potential _drift_ in the future, leading to discrepancies.

**Context:**

I was responsible for introducing this code duplication while fixing #210 so I can also be responsible for fixing it :)

**Comment by shashank025** [comment]
FTR, I can take this one :)

**Comment by eliblock** [comment]
I think you're aware of this - since you've already touched the code - but let's see if we can apply the same fix to the `PARSE` stage!

**Comment by shashank025** [comment]
Oh yeah, I do intend to fix the PARSE stage too, forgot to mention it!
