### ISSUE TITLE
improve il/juvare with opening hours and notes

### ISSUE THREAD

**Issue by yotann** [CAVaccineInventory/vaccine-feed-ingest#297]
Blocked on #205. The il/juvare stages can already get all the important information from the main JSON file, but there's a bit of extra information we could add by scraping other pages. Specifically, by scraping the sign-up forms for each site, like [this one](https://events.juvare.com/IL-IDPH/9c613793-7b66-4f0c-8f2e-09c30d953ad0/), we can get the opening hours and additional notes for each site.

The sign-up form URLs are generated by the existing normalizer (see `_get_contact()`), but they would need to be fetched, parsed, and normalized. It looks like there's one page per month per site.

Some other pages I found that don't seem very useful:
- <https://events.juvare.com/IL-IDPH/> just looks like a subset of the info we already have. Unless the [past events](https://events.juvare.com/IL-IDPH/?old=1) are useful somehow.
- <https://events.juvare.com/IL-IDPH/events/ical/?locale=en>: very large iCalendar file that lists every sign-up time separately. Doesn't include notes, though.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
