### ISSUE TITLE
CVS store id not correctly parsed

### ISSUE THREAD

**Issue by shashank025** [CAVaccineInventory/vaccine-feed-ingest#300]
There's a slight regex bug in [provider_id_from_name()](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/589f7c991017c5f20d722fd774112262df4b9251/vaccine_feed_ingest/utils/normalize.py#L8):

**Repro:**

```
>>> from vaccine_feed_ingest.utils.normalize import provider_id_from_name
>>> provider_id_from_name("CVS 104")
```

**Expected Behavior:**

```
("cvs", "104")
```

**Actual Behavior:**

```
("cvs", "4")
```

Also, the following line in a test case will need to be updated: [tests/test_provider_id_from_name.py](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/589f7c991017c5f20d722fd774112262df4b9251/tests/utils/test_provider_id_from_name.py#L17)

**Comment by cdjj** [comment]
I can take this.
