### ISSUE TITLE
normalize arcgis from Montana

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#52]
[![learn our pipeline: normalize](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=normalize&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#normalize)

Normalize existing [`.ndjson`](http://ndjson.org/) records into [the Vaccinate The States data schema](https://github.com/CAVaccineInventory/vaccine-feed-ingest/blob/main/vaccine_feed_ingest/schema/schema.py).

Read all files in the directory passed as the second argument (`sys.argv[2]`), transform each record into the normalized schema (filling in as much detail as possible), then output them to new files in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the normalize stage and how to get set up for development!

### Tips

1. Fetch and parse data for this site before you start developing:
    ```sh
    poetry run vaccine-feed-ingest fetch mt/arcgis
    poetry run vaccine-feed-ingest parse mt/arcgis
    ```

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest normalize mt/arcgis
    ```

### Example
[Parsed files for `ak/arcgis`](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/parsed) are converted to [normalized files](https://github.com/CAVaccineInventory/vaccine-feed-ingest-results/tree/main/ak/arcgis/normalized)

**Comment by ericrobinsondev** [comment]
On it

**Comment by ericrobinsondev** [comment]
The data coming from the parse stage doesn't seem to be correct. 

The `site` data being picked up is:

```
{'ACRES': 1318836.63209185, 'ALLFIPS': '30009', 'BAS_ID': '23000900000', 'COUNTYNUMBER': 10, 'Date_Reported': 1618747200000, 'Dose_1': 3913, 'Dose_2': 3021, 'Doses_per_1000': 744.9, 'Eligible_Pop': 9145, 'FIPS': '009', 'GLOBALID': 'bf9ac01a-0a9b-4e3f-b85d-a284efe816da', 'LAST_UPDATE': 1476489600000, 'NAME': 'CARBON', 'NAMEABBR': 'CA', 'NAMELABEL': 'Carbon', 'OBJECTID': 1, 'ORIG_FID': 28, 'PERIMETER': 265.76331638, 'PKEY': '306101002.BND.10', 'SHAPE__Area': 10762096330.1758, 'SHAPE__Length': 607125.306564405, 'SQMILES': 2060.68223791, 'Total_Doses_Admin': 6812}```

**Comment by eliblock** [comment]
Hi @ericrobinsondev - you're right, this doesn't look like vaccination location data! [The original source link is here](https://montana.maps.arcgis.com/apps/MapSeries/index.html?appid=7c34f3412536439491adcc2103421d4b), it looks like it shows how many vaccines have been administered in various counties, but does not show where to get a vaccine.

I'm going to close this out. Thank you for preventing bad data from making its way through the pipeline!

**Comment by MoralCode** [comment]
seems like there are no other map layers under the services page for MT that look like they provide vaccination locations based on the name( link: https://services.arcgis.com/qnjIrwR8z5Izc0ij/ArcGIS/rest/services)

**Comment by MoralCode** [comment]
The state seems to not provide vaccination site locations, but these states may be covered by existing national datasets (mainly the one from GISCorps) that's based on crowdsourced locations. My recommendation would be to either encourage the state to make this data available or contribute info on sites in MT state to the GISCorps dataset (link: https://covid-19-giscorps.hub.arcgis.com/). They have forms for single-entry and a spreadsheet template for bulk entry and their volunteers validate it. Once the data is in the GIScorps system it will get pulled in by this repo

**Comment by obra** [comment]
Just as a matter of policy, we would probably rather incorporate and publish that data directly than run it through giscorps

**Comment by MoralCode** [comment]
fair. in that case maybe it would be useful to set up a google form and/or google sheets template that people can fill out and submit for verification before it gets added to this data set.

If there are resources available for something like this, i believe google sheets has a way to download a sheet in csv format. using the normalized schema for the columns and/or google forms questions should make the fetch/parse/normalize flow really easy. 

just some thoughts in case this ever gets actually implemented
