### ISSUE TITLE
fetch or/getvaccinated_gov

### ISSUE THREAD

**Issue by MoralCode** [CAVaccineInventory/vaccine-feed-ingest#714]
[![learn our pipeline: fetch](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=fetch&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://getvaccinated.oregon.gov/get_published_events

Put your script in a file named: `or/getvaccinated_gov/fetch.sh`

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

## Notes:

this is the data source behind https://getvaccinated.oregon.gov/#/locator?lang=en and doesnt seem to be part of the scraper yet. 

It probably doesnt contain much new information TBH

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch <state>/<site>
    ```

**Comment by MoralCode** [comment]
I am dumb and only submitted this to github. it has now also been submitted to the airtable for approval. Whoops.

If the correct process for this could use some documentation, let me know

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
