### ISSUE TITLE
normalize individual locations more independently from each other 

### ISSUE THREAD

**Issue by MoralCode** [CAVaccineInventory/vaccine-feed-ingest#814]
**Current behavior**: if a single location within a scraper fails validation or due to some other reason, the whole scraper will be skipped (unsure if its just the locations after the failure point or all locations from that scraper) and the error gets logged/reported.

**Planned behavior:**  if a single location within a scraper fails validation or due to some other reason, the error gets logged/reported for that location and the rest of the scraper will continue running in case the issue is a one-off with that single location (i.e. typo on the part of the person entering or reviewing the data for inclusion in their dataset to begin with). If more than a configurable number of locations within a scraper fail, the scraper itself will fail to prevent spamming the logs with _too many_ individually-failed locations.

**Implementation plan:** the code that iterates through the parsed locations to normalize them is - in my experience - located generally at the bottom of every normalizer making this kind of change difficult. Since many of the scrapers i have written are copy-pastes of each other (and i assume many other scrapers are too) I think it makes sense to factor this "iterate through every parsed location" code out of each individual normalizer and into a helper function in the `utils/normalize.py` file.

**Benefits:** This would remove a substantial amount of duplicate code and  make it easy to add the feature described above to many scrapers at once. It will also make it a little easier to run a full-scale "run every scraper" test on someones local machine as a way of testing every scraper to find and fix bugs faster.

wanted to post this here as an opportunity for people to discuss this. I'm happy to implement this with some smaller scrapers fist if a slow, incremental migration would be preferred.

**Comment by eliblock** [comment]
Closing all issues: https://blog.vaccinateca.com/vaccinate-the-states-is-winding-down
