### ISSUE TITLE
Build regex to produce links from CVS store IDs

### ISSUE THREAD

**Issue by nschiefer** [CAVaccineInventory/vaccine-feed-ingest#85]
In `utils/normalize.py`, we have a function `def provider_id_from_name(name: str) -> Optional[Tuple[str, str]]:` that tries to pull out retail pharmacy store IDs from names. This is a very reliable way to match.

We don't currently have one for CVS, and it would be great to have.

**Comment by cdjj** [comment]
Pull request coming in a moment.

**Comment by cdjj** [comment]
We can close this now that the PR's in.
