### ISSUE TITLE
fetch myspot_gov from North Carolina

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#87]
[![learn our pipeline: fetch](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=fetch&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://myspot.nc.gov/

Put your script in a file named: `nc/myspot_gov/fetch.py` (other scripts okay, like `fetch.sh`, etc.)

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch nc/myspot_gov
    ```

**Comment by rreichman** [comment]
I'd like to take this issue please.
