### ISSUE TITLE
fetch tableau from Louisiana

### ISSUE THREAD

**Issue by eliblock** [CAVaccineInventory/vaccine-feed-ingest#94]
[![learn our pipeline: fetch](https://img.shields.io/static/v1?label=learn%20our%20pipeline&message=fetch&style=social)](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Runner-pipeline-stages#fetch)

Fetch data from: https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop

Put your script in a file named: `la/tableau/fetch.py` (or `fetch.sh`, etc.)

Store it (without processing) in a new file created in the directory passed as the first argument (`sys.argv[1]`).

Check the wiki to learn more about the purpose of the fetch stage and how to get set up for development!

### Tips

1. While working on your code, run it at any point:
    ```sh
    poetry run vaccine-feed-ingest fetch la/tableau
    ```

**Comment by krouskop** [comment]
Not clear to me if this is an ask to retrieve data from the literal URL "https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop%20;%20https://ldh.la.gov/assets/docs/covid/LACOVIDVACCINE-LOCATIONS.pdf"?

That URL loads an effectively empty page for me:

![image](https://user-images.githubusercontent.com/3890555/115947852-84819080-a498-11eb-9d56-e08c51ecce16.png)


However, in a separate comment I'll share some findings from looking at https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop

**Comment by eliblock** [comment]
Hi @krouskop - sorry about that! It looks like I copy-pasted this incorrectly out of our tracking system.

`https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop` (the url you found) is the right one for this. I'll update the main post!

Are you interested in taking this one on?

**Comment by krouskop** [comment]
The page https://public.tableau.com/profile/lee.mendoza#!/vizhome/pharmacies_desktop/Pharmacies_desktop loads as:

![image](https://user-images.githubusercontent.com/3890555/115947891-b266d500-a498-11eb-9357-365d931ad448.png)

The Vaccination Sites piece of that is an IFRAME to the URL https://public.tableau.com/views/pharmacies_desktop/Pharmacies_desktop?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0#navType=0&navSrc=Parse

![image](https://user-images.githubusercontent.com/3890555/115947918-d5918480-a498-11eb-9500-3aa0a502d7e4.png)

The IFRAME in turn loads a JSON feed from a POST of form-encoded data to https://public.tableau.com/vizql/w/pharmacies_desktop/v/Pharmacies_desktop/bootstrapSession/sessions/7C17ABF5F8324938B6D324D997A96291-0:0.  However, that last bit in that URL is a session ID that's unique from when you load the page.

`curl --silent -I 'https://public.tableau.com/views/pharmacies_desktop/Pharmacies_desktop?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0#navType=1&navSrc=Parse' | grep '^X-Session-Id'`

will bring back a valid session ID.

e.g.:

`X-Session-Id: C43BFD5A350C45CC9AB8B3F4981DC2B0-0:0`


Next is doing the post to that https://public.tableau.com/vizql/w/pharmacies_desktop/v/Pharmacies_desktop/bootstrapSession/sessions/$SESSIONID.


That is POST-ing these form params:

`worksheetPortSize=%7B%22w%22%3A1375%2C%22h%22%3A480%7D&dashboardPortSize=%7B%22w%22%3A1375%2C%22h%22%3A480%7D&clientDimension=%7B%22w%22%3A1395%2C%22h%22%3A507%7D&renderMapsClientSide=true&isBrowserRendering=true&browserRenderingThreshold=100&formatDataValueLocally=false&clientNum=&navType=Reload&navSrc=Parse&devicePixelRatio=1&clientRenderPixelLimit=25000000&allowAutogenWorksheetPhoneLayouts=false&sheet_id=Pharmacies_desktop&showParams=%7B%22checkpoint%22%3Afalse%2C%22refresh%22%3Afalse%2C%22refreshUnmodified%22%3Afalse%7D&stickySessionKey=%7B%22capabilities%22%3A%226500f110%22%2C%22dataserverPermissions%22%3A%2244136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a%22%2C%22featureFlags%22%3A%22%7B%5C%22MetricsAuthoringBeta%5C%22%3Afalse%7D%22%2C%22isAuthoring%22%3Afalse%2C%22isOfflineMode%22%3Afalse%2C%22lastUpdatedAt%22%3A1619028990220%2C%22viewId%22%3A40403805%2C%22workbookId%22%3A7121703%7D&filterTileSize=200&locale=en_US&language=en&verboseMode=false&%3Asession_feature_flags=%7B%7D&keychain_version=1`

However, paring that down to JUST the `sheet_id=Pharmacies_desktop` seems to work fine.


Which lands us on:

```
curl 'https://public.tableau.com/vizql/w/pharmacies_desktop/v/Pharmacies_desktop/bootstrapSession/sessions/ < SESSION ID HERE > ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: application/json' \
  -d 'sheet_id=Pharmacies_desktop'
```

**Comment by krouskop** [comment]
@eliblock - I won't have time to get Python 3.9 and Poetry installed tonight. So will turn this back to someone else to pick up.

But, I believe per the above comment, the two curl commands:

`curl --silent -I 'https://public.tableau.com/views/pharmacies_desktop/Pharmacies_desktop?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0#navType=1&navSrc=Parse' | grep '^X-Session-Id'`

to grab a session ID, and then using that in:

```
curl 'https://public.tableau.com/vizql/w/pharmacies_desktop/v/Pharmacies_desktop/bootstrapSession/sessions/ < SESSION ID HERE > ' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: application/json' \
  -d 'sheet_id=Pharmacies_desktop'

```

will bring back this data.


Hope this helps!

**Comment by eliblock** [comment]
This research is phenomenal - thank you for getting it started! FYI - when you do get around to setting up your environment - [don't miss the setup script](https://github.com/CAVaccineInventory/vaccine-feed-ingest/wiki/Development-environment-setup) which you can run (or use as a reference for a list of commands).

**Comment by cdjj** [comment]
I can pick this one up.

**Comment by cdjj** [comment]
Ugh, this is awful.  Once you get the data from sessions/SESSION_ID, there's no JSON there --- it's pulling down the data as PNGs!  Take a look in a browser's network-debug mode and you'll see lots of requests for views.*.png; they turn out to be tiles with the text.

This one's beyond what I can pull off tonight....

**Comment by cdjj** [comment]
Unassigning in case anyone's got better ideas on how to approach this.  At the moment, the least-bad options I can think of are (1) getting in touch with the dashboard owner and asking them to provide something more useful or (2) doing text recognition on the tiles, and that's beyond what I can pull off in my available cycles.

**Comment by cdjj** [comment]
FWIW, it looks like Louisiana is taking all this data from a PDF (https://ldh.la.gov/assets/docs/covid/LACOVIDVACCINE-LOCATIONS.pdf, linked from https://ldh.la.gov/covidvaccine-locations/), so maybe trying to extract from there is going to be more productive.

**Comment by obra** [comment]
@simonw You have tooling for this right?

**Comment by jason-riddle** [comment]
One idea is to use tabula-py to convert https://ldh.la.gov/assets/docs/covid/LACOVIDVACCINE-LOCATIONS.pdf to a table. I'll see if I can throw something together.

**Comment by jason-riddle** [comment]
So the tabula approach sorta works. I'm able to parse the pdf into a csv and then into a dataframe. But the row height varies in the pdf. On the first page "Acadia - Carmichael's Cashway Pharmacy - Crowley", "Ascension - ** CVS Pharmacy #5278", and "Ascension - Viallon Drug Company - Donaldsonville" for example use double the height compared to the other rows. Tabula handled "Acadia - Carmichael's Cashway Pharmacy - Crowley" fine, but split "Ascension - ** CVS Pharmacy #5278" and "Ascension - Viallon Drug Company - Donaldsonville" across three rows, 14 15 16 and 17 18 19 respectively. I'm not sure how to clean this up.

```py
# Install in colab.
# !pip install -q tabula-py

import tabula

pdf_path = "data/LACOVIDVACCINE-LOCATIONS.pdf"
csv_path = "data/la_locations.csv"
tabula.convert_into(pdf_path, csv_path, output_format="csv", pages='1')
df = pd.read_csv(csv_path)

import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

result = df.copy().head(20)
del result['Parish']
result.columns.values[0] = "Parish"
print(result)
```

```
       Parish                                 Facility             Street Address            City                                       Website           Phone
0      Acadia            ** Acadia St. Landry Hospital      810 S Broadway Street    Church Point                                           NaN  (337) 684-4262
1      Acadia          Church Point Community Pharmacy          731 S Main Street    Church Point           http://www.communitypharmacyrx.com/  (337) 684-1911
2      Acadia     Thrifty Way Pharmacy of Church Point          209 S Main Street    Church Point                                           NaN  (337) 684-5401
3      Acadia        ** Dennis G. Walker Family Clinic         421 North Avenue F         Crowley                http://www.dgwfamilyclinic.com  (337) 514-5065
4      Acadia       ** Walmart Pharmacy #310 - Crowley       729 Odd Fellows Road         Crowley          https://www.walmart.com/covidvaccine             NaN
5      Acadia                           Biers Pharmacy     410 N Parkerson Avenue         Crowley                                           NaN  (337) 783-3023
6      Acadia  Carmichael's Cashway Pharmacy - Crowley    1002 N Parkerson Avenue         Crowley                                           NaN  (337) 783-7200
7      Acadia                     Crowley Primary Care         1325 Wright Avenue         Crowley                                           NaN  (337) 783-4043
8      Acadia                   Gremillion's Drugstore            401 N Parkerson         Crowley         https://www.gremillionsdrugstore.com/  (337) 783-5755
9      Acadia                       SWLA CHS - Crowley  526 Crowley Rayne Highway         Crowley         https://www.swlahealth.org/crowley-la  (337) 783-5519
10     Acadia                 Miller's Family Pharmacy  119 S 5th Street, Suite B            Iota                                           NaN  (337) 779-2214
11     Acadia                    Rayne Medicine Shoppe          913 The Boulevard           Rayne      https://rayne.medicineshoppe.com/contact  (337) 334-3399
12      Allen     ** Allen Parish Community Healthcare             108 6th Avenue          Kinder                    http://www.allenhealth.net  (337) 738-9494
13      Allen         Walmart Pharmacy #1107 - Oakdale         1900 Highway 165 S         Oakdale          https://www.walmart.com/covidvaccine             NaN
14        NaN                                      NaN                        NaN             NaN   https://www.cvs.com/immunizations/covid-19-             NaN
15  Ascension                    ** CVS Pharmacy #5278          20 W Tenth Street  Donaldsonville                                           NaN             NaN
16        NaN                                      NaN                        NaN             NaN                                       vaccine             NaN
17        NaN                                      NaN                        NaN             NaN  https://www.facebook.com/Viallon-Drug-Co-of-             NaN
18  Ascension    Viallon Drug Company - Donaldsonville         309 Marchand Drive  Donaldsonville                                           NaN  (225) 725-4288
19        NaN                                      NaN                        NaN             NaN               Donaldsonville-105102667610177/             NaN
```

**Comment by neonquill** [comment]
I made an attempt to use https://github.com/bertrandmartel/tableau-scraping to scrape the original Tableau site, but didn't have much luck. I can get `ts.loads("https://public.tableau.com/views/pharmacies_desktop/VaccinationSites")` to complete but nothing after that would work.

The [Server side rendering](https://github.com/bertrandmartel/tableau-scraping#server-side-rendering) section seems relevant for this site. I didn't manage to figure out if there were any filters available to use. All of the example sites had some type of interactive filter on them, which is what I suspect that README is referring to.

I've run out of time to dig into this, but I suspect this is a dead end.

**Comment by nuchi** [comment]
Extended @krouskop's work:

```diff
  SESSION_ID="$(curl --silent -I 'https://public.tableau.com/views/pharmacies_desktop/Pharmacies_desktop?%3Aembed=y&%3AshowVizHome=no&%3Adisplay_count=y&%3Adisplay_static_image=y&%3AbootstrapWhenNotified=true&%3Alanguage=en&:embed=y&:showVizHome=n&:apiID=host0#navType=1&navSrc=Parse' | grep -i '^X-Session-Id' | awk '{print $2}' | tr -d '\r')"

  curl "https://public.tableau.com/vizql/w/pharmacies_desktop/v/Pharmacies_desktop/bootstrapSession/sessions/${SESSION_ID}" \
+   -d 'renderMapsClientSide=true&isBrowserRendering=true&browserRenderingThreshold=9999999' \
    -H 'content-type: application/x-www-form-urlencoded' \
    -H 'accept: application/json' \
    -d 'sheet_id=Pharmacies_desktop' \
    -o /tmp/response.txt
```
The above is sufficient to get the data. I can open a PR later unless someone else gets to it first!

Parsing looks like it'll be a nightmare though unless the library that @neonquill posted can somehow be adapted to this weird JSON blob.

**Comment by cdjj** [comment]
I had a couple minutes free and turned @nuchi & @krouskop 's work above into a PR.

**Comment by eliblock** [comment]
Great work from everyone involved in figuring out how to download that JSON(ish) blob!

I just ran #229 locally (I encourage you to do the same), and I'm not sure that we're going to be able to parse the resulting blob (or at least, certainly not easily).

Here's a sample of the data pulled from that download:
```json
{
  "dataType": "cstring",
  "dataValues":[
    "** Acadia St. Landry Hospital\n810 S Broadway Street\nChurch Point LA ","** Dennis G. Walker Family Clinic\n421 North Avenue F\nCrowley LA ",
    "...", 
    "(337) 684-4262","(337) 514-5065","(337) 783-3023","(337) 783-7200","(337) 684-1911","(337) 783-5755","(337) 334-3399","(337) 684-5401","(337) 738-9494",
    "..."
  ]
}
```

All the information seems to be in a flat array 😫 , and while there are several "indices" attributes later in the data... it looks like it's going to be a big puzzle to figure out.

Given this, I wonder if the PDF approach suggested above would be easier to handle? (If the only issue is rows of varying heights, we could greedily consume rows which have `NaN` parishes... or something).

What do others think now that we're able to see the data?

**Comment by jason-riddle** [comment]
If anyone wants to play around with the PDF approach, I put together a Google Colab here: https://colab.research.google.com/drive/1SqbmxZJNeC7_MUNcQJbKCBnHXP2UIzQL.

**Comment by cdjj** [comment]
I'm going to try playing with the data from #229 and see if I can get anything useful out of it, but ... yeah.  Multiple parallel efforts here seem warranted.

**Comment by nuchi** [comment]
I got the data using the library @neonquill suggested. I'll see about opening a PR — I'll branch off of #229 rather than main.

**Comment by cdjj** [comment]
OK, having looked at this, pulling out locations and addresses is easy, so I'll throw that together now.  I _think_ I have some understanding of the JSON format, but reconciling locations to phone numbers & websites will be a bit harder.

**Comment by cdjj** [comment]
OK, PR #232 is a first cut at pulling data out of the quasi-JSON.  It's ugly, but works.

**Comment by nuchi** [comment]
Added my own PR #234 as well — sorry to duplicate work! I did manage to get phone numbers.
